apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- sealed-backend-secrets.yaml
- sealed-frontend-secrets.yaml
- sealed-platform-secrets.yaml
- sealed-custom-db-ha-secrets.yaml
- sealed-ghcr-secret.yaml
