---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secret
  namespace: monitoring
spec:
  encryptedData:
    smtp_auth_password: AgA2+yp7SjotpVrxoIzJhJoDDzrWqDctly7WMffaeiR9POgxANnnKp8ty6jynwqwIPRwA/AEiMuxtbKkGXYRRZLn94KzhPaAK19XxR5BpmxC3eHWH2uMbB37IpUst/ob8Akzd9YoE/5xEr6EPNOQPjCGDMhTQDh+aDDPdKoeM+hv+YSTeqkKnF8pV7n2PTxXi9j7hV7H8p1FqqvApNOe87/L2/eeslKk0qBySMgVE5W7P1TLqJQx21cUry2kxDTYZsXNDLmjEi09iCUa3jCoebkJBjSqmoDpf/UX5vc+b7YEiP5/4+y73jluKp+FTHC5GqS3DyWFwHVE7WKS+uvi75XymLjidcBC3Xwl9Ks5ImqXyRKvQvZ0nSczQ6ac4HPheAu88sxYUKI0gujI9j0Yn8mrXE/n1S9r7fcCj7ilNIusLUVw+WRgQaqVMSQxkiYeIayrhXv+c8GEQZ4HAJUiwTiV/UcfYxURYjZEg0O2VWRbwYS+3eStVbo5ZItYX0f9JVuUbASfhl+l/GynU4UaUtccijaRdrlWyMvl5ZLqnWg6wpt1nKvl3gva3JQgNWyOCh3QSSfY63SWAA94Q2Ap0MYM6PtUN50AEZTw8c5hWMtWFDKQuzgbSkgSmVI4+dVxGzkzVLcZaFvL+DZnvg7zgUAG6Hrc0xksFC+LymfG6s7bxlcNgnQAFxyjyoyOfHYSUu+JraJ5TjJSJZncWwFtXeBoGOjK
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secret
      namespace: monitoring
