---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: bookit
spec:
  encryptedData:
    .dockerconfigjson: AgA0xJQADUsYDb3S4Q4wTu3egUmkgIhxnhRbAGwTB7FBv6snXV1n3dl6LLSNq60qDq2jiRXQGmdrPXg/MrG9F0OBTmNk3n/AQypVphUvDb+zhz//AzsJwk1ch11+1oEiJQTKxl/MCmmMfcC7VePEhPHD9Pby8K8X2jdXi5I9mJXT4trFEnRJQM/eTZUnvffYpT7vM3S6vWGliINWIvUBWmrUvIDyro59TXX8zF+9Ru6oHsq9dmZ2OX+nU5ZjBFQ0WeOK1tWxlNDH5zfZOdKvTlSzo69LDrL6HUFn8tWDYbELq4lgycbdJjwoVm0R6PH9bGlGaclxbj7BGwnbLEbQaiKeGdBS5AaXamLFi7HcG+o6GEZ7aXtR1NKnNJbWXSAcICYRn4+NpGpmBqRx/1UrG2b294Wu513d3hhLkmSkwwDPmYLVLZnAYUvaNzeQLIRQ+IRFPwBVw3IOabmslwuN7axdkwXPPGTKWW9lfqP8sGhdhChAgjvXX1VWyKN1SEV3NuPv9RMZVNdDubWvEzGY1vREePcYtiyBLUDb+Xty+74oTuqWaVcLtaZR1YnPxqDEk5Ru2kVuD/6RPpJCRX399XT109MBhwglZkpY6WcjIQ+cauB+cBJOZTzLY8NjXkZ/wPafccEh/U+JXQOHk/X/gawuRmqG7LOXUutycshBbAP5lIE1/nQ1G2eDgpZ/C7u+3x6X0tr4NfkQZoYgdRo8OftGOXVlqqepo3z3RoFN54D3l4B5YiZbi75NTJylCqhKRsBCa5gj9NPyBApuSzJ7wrcd7D6lsH96jg01n9His0m5EmP47vBJjalTnkPzmoKoUqszGPzwJtrHIvn3IXcxFGGdnQZBoalIYklAgB7Wz7gn5CBWC7mr4z+bIGrptIceXTytis3nfIlljCh49YfHDTmPFeSt5PT4h3qYJBvwr65svfSSe1t5HE3LdUqHFJmdN3zBaXtC7mIugac7WDdTUDUN/Fe6usUAwGN//9OqNJwwFKmEtaV7hydWauygNJJaKS2qxD7XiFwz6oQ3TXjz2pPu1+pfoEV/vXZlbSEly/speROdKnVQvGIg34M6egCYNq2lSZru6RTErADxSH++iWSr
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: bookit
    type: kubernetes.io/dockerconfigjson
