---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: bookit
spec:
  encryptedData:
    .dockerconfigjson: AgCW2qieHGkQlqup0lom04+lXc624EnWlAK/SfBLttERalQz/ujzmN2BC4TDDnHdyT3ttjC80Xtn2YuzGYMbYK15WsU4LzaNQ6a3QLiIHp5S2P16+wWZZU1Gw9BxuBGadrMI0gy9TOI74bP/ZaUlYngE5tWXlAlSgYONsTQCav3+y4JDusoGyGJ6r9MHo8IbEiTsbjQacFLJqMNqKNn2xBRqlgnJzRqUGLNpG/5cZwbPUkT/s4IVUv03KFTpH5NBQ5QD3gMoB46NaAxuQvEk2UGaHCOz3kS2YJYYVBuSdrnRK5qL8zeiyPqE4cR3SD0C1T7BvL1/SBPc6s+TxOh3sfdkXUyTRjtK+Jla5emJu1OlHPRNw5KkMn8eodX7ypduK6mVqgz9OXNL7nfuiS8mQvYO9RdihgtC2kCywuYExgqXWWQJFqOSrjuYMiaX9vDZlVP7Q+pibeXmDcNNWlHqUuvl+6182wVexkGgMg0D4wso848HrznITsJaMIVegwAQNqUqMaR5sf7Z+ZGKGEKWnt0JuYdqbLr8z3qBcNXyrihInUs7qvVn02hNona69jHpY/3jevUThfR1JY490gwnp47pJfRchD1Xf4SsrwTgM3Tx7k3VyjSJX00SKtDehlgTPnHWXUzaM12uctxjJB4vKMz9pUMTJLNxj90aY9Nlq1UvifSjV/vhoIFOIH7tNXwcsQZ1/E0qhrG+MvbgcaCjLQaE0psd87OSsYj6oCq5WBlTX+mwfM1ymmdg2yoITV9+PePwnqUzTK3Zypd0x2leWyzpe9YKO9RfSubNQIEqyBf16+Sf32R1HUvuFB3WSnQCs3Bv1xaOFz7q7R+YilPcF8sBeaaQopqXwVp/azCbEPYS+M4/znYYhS/y8mT9pTNo/gMWY1tPRyMZDDlAeCytRtr2wMUvR9D8PL6xHfcGdUVkqTctGKUb6diEBTzEHCqta+l9ErMRkoeGgrnMqohUJ7LXe47IvaMSEzOArSSQkFhMaoT4THJuG+fTyvDZUadKTn2jKJJRZvFgEnje/frIelswmoAQhjB77gXOTtAMAYrLOMnjAg0r2YT2nnxttaF2gxFE+xHRj9MElPRIf7Ygqahr
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: bookit
    type: kubernetes.io/dockerconfigjson
