---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-secret
  namespace: bookit
spec:
  encryptedData:
    .dockerconfigjson: AgAKFbmbI0XBZVFcHM7GtgHc9nSiD9UrUoqvmfHt6coTyK0Ed+RBsNj85KzkgURGBpA6P5lvPD8FC7OCfEOWuat7+9ZV0AsfHIrGt0hfQ9EHe+8ZeY6HSIH58cEDMJFuGvbke6MSAuX+kZpfxpX868DuIVPr3uHU4XtscQx4fd7RwT23iOhUdD2Ed+7s+CljWca9IYHx2rf4RruKZCQhei5uc8wrjzpYgAJ5xjFvW1rfcjVL97gqs7cZ1JszYW7hGObImeEfQQuPj2B+5JEm0QpNAynZ3c3IUAPi0iRO8jmDMEUs0yonQUEhRmBpco+LugoaVGjc95qsDTwZFF+0YhgBPYZ8FaDFJLOSJcEtYAAmKh3EF0mrjMpIxVkavpGy2kigiDX5f309xJGR+xiXlzqD9Ai0ZRxnmmsYIZwk8pwI0xyLZ47vhQElbO4TiA+M78uJCjN2NS8W3G6W/tN2US1UL+81oyu+3FGbKfptfgeeLz6lPSXFPvz5Lz9SRmNnlAlmTCyOjDUHHcCTvdaaAfeXyvtHmEoD+YRha9z7hG1QyCmwR/K8iv/A7+Wk20ag4qqpyG1DEI9F58DKNdWnWMPmu+bq6p5EmELJmy8KZSPXg+OWCgz/zsSdp+yqWYUF2k54N3QoNe7XIOxG+fQRP47pW1iVMML/JUJzGPdFEQs/QFDNEksicFWmLgbnTBhVgnVjf3a4DP8q6Ogm/ZfRnmjHZD+cVL8vx394sxJeQCydVvdjZla2GVAMd2tNeYSyNr9oix8wBNphwhT94DuEAjzbvb8dX3IdeTGeOc2lD24yNWNiLGr4ourjkOHpdxjVlKT0+P00oCYkI8tpUpEwxQNxqTpnl2wWQY4/x8aNLjBfznA7J+kn3aZRtyOF/BGVmrhqsU6w0jKVqmRvY5PZ+UCx3dJPSzv0k5P1GwlY+W/vFMCO+6SN49MXUDP66TIWbcf7LCw9D9dZMpLelJP25nPF9Ez7Oi5ROnewrRhhtwiQyNPDUFS4csojChCjFe1D5MPnljWkXS+fQMYoH3A6BN8q9QKlQOeP4XlBUKhu14vDF4ZYsb4XgVdYDpJPoIKhGuyxDvzTEuL192kPGPjQ1mRV
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-secret
      namespace: bookit
    type: kubernetes.io/dockerconfigjson
