---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secret
  namespace: monitoring
spec:
  encryptedData:
    smtp_auth_password: AgBELIEBmEH+5TWOxgUCgkr2NajDgjlErt7P7qrMc3aJqGuMBmLKBaP8MlUxswZyZ+kUD8sQgHGjq9+OrQjit5qzKBFthDliM7M4pe7UNw03ZozGKI+kCf3hnIPhVTRK+jDrMm3CpYGM7nGxmmUUENAjwFd8FzUms4LDmSbzi3mzDWV462rnJ4MPebtOcMJFSkR474thHEktygl5ccnF9K202/5raw9+etqoOQAVPz7tIMdPpVOUX+lEUBaNfNqNRMpCecfJIPeesnvSzRUSxkHT/QCmPIQHth/UTNhqUMVv6t1qIw1URz3HqV5+2WCRL1lJiaREGWLQD3FDd+bUXcnqY3wVUNGBTKtt+wEbj0j5E3e7MoGvjcaYZaEAq1xAoDA2pbEkqwAktCAw3VUhbW2R0hYk1V3vvdB9Jl2RfaLBPSa/O4LBv4TgGEEHhqz705DaISmKDb8BJ1H0rQYOtlrbfhSPkXvxjN5IHsceS6b8oguAc0WUhAgOf7WjPWpA1skT4UFR0jN1obmc5TOy+BrZOJzw2YHK4oY3aLLt0oxa1lNNfyvtR1KiY0HwNgmxiNuGn+CmwMDV4oqYRZsrbWQa3ZZ/U5+vEyUPY5gtOoTVLUWCKVV8sJjBPowdYRxrx6Rfg6QD0ktl0PI3aDrn0S9wvqblSoXpR3rBqx7H6i4BHR0MYlO36SGKVuznBuGexOjLluWqSqgorg7w6sbb6PQfyf01
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secret
      namespace: monitoring
