---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-secret
  namespace: monitoring
spec:
  encryptedData:
    smtp_auth_password: AgCEKS1Zldi9oLZfO9R1/bFGJtrs/RGwy5wMpj3jyiZnbSfyhaUkNOtvBEPpxPkjWzYu0J6JrezXpvMlDgONeFRHS9V/1ufArv3z6barlZmpAEXGdbPVEGA5EQj/IuMljftKA7MiWNOBzXSnF1RRoLXMwNyf/PWCoOxyPVgIZnB29CajFhR/0leeHq2ek1tCxtyjrzWI5rDrj/MyTN/ZxLCpVo8Pa/6cprVf6kECDHJpgerZi3AlyUIZze7j+QxYemx/4rPkFIaEWjnqzqihcWywDd0UXsINI9C4afyF9l/khVtC/40QZVlH2VB8F3X9Mm7vMpYBNVk/KLx2mGRXUzW7VsNkeQW5YHZAo7eBGEA3DGqnznk3lvpByrCJXEH0Xo/U+4QctRO/uTVSSJEQGh/ggzFEoQy3iQgxnCpvZqi0B8ozm4dJQ+SPzag567p4el0Ty/k8+iE4XZTHZo6zmZOazV4Ft0D0CuyvTfwXFtvTKCvQUpfwj4qIaFE5is3xaU8UMcFWOP2Ii6BcIiIAsRcTn9Lgw/88D4KU2H4k9MAVoruPt05TqmALg5CCnsubKropUq9fNySN9z7lIedluTzlxJEiXo77aGsrDyZ9yKENaSMiM0bWn/HHftV/5538AufxKOzppW8kQu7ehG9xYdzbOkAvGvtH8VY084FKioBe3zs77inGYt1H55Se4nAgdhKjl71NQT4P6GnXnLHnJf37LKxX
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-secret
      namespace: monitoring
