$patch: delete
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lock-server-hpa
---
$patch: delete
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: payment-processor-hpa
---
$patch: delete
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-worker-hpa
