{{- if not .Values.rabbitmq.useCloudProvider }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-server
  namespace: bookit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: rabbitmq-server-tls
  duration: 2160h
  renewBefore: 360h
  dnsNames:
    - rabbitmq
    - rabbitmq.bookit
    - rabbitmq.bookit.svc
    - rabbitmq.bookit.svc.cluster.local
    - rabbitmq-nodes
    - rabbitmq-nodes.bookit.svc
    - rabbitmq-nodes.bookit.svc.cluster.local
    - "*.rabbitmq-nodes.bookit.svc.cluster.local"
  usages:
    - server auth
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: rabbitmq-ca
    kind: ClusterIssuer
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rabbitmq-client
  namespace: bookit
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretName: rabbitmq-client-tls
  commonName: bookit
  duration: 720h
  renewBefore: 168h
  usages:
    - client auth
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Always
  keystores:
    pkcs12:
      create: true
      profile: Modern2023
      passwordSecretRef:
        name: rabbitmq-client-keystore-password
        key: password
  issuerRef:
    name: rabbitmq-ca
    kind: ClusterIssuer
{{- end }}
