apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server.yaml
  - custom-db-ha/rabbitmq-ha.yaml
  - databases/db-backup-cronjob.yaml
  - databases/redis-cluster.yaml
  - monitoring/prometheus-grafana.yaml
  - monitoring/otel-collector.yaml
  - monitoring/tempo.yaml
  - multi-region/postgres-operator.yaml
  - multi-region/mongodb-operator.yaml
  - multi-region/external-dns.yaml
