apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metrics-server.yaml
  - custom-db-ha/rabbitmq-ha.yaml
  - databases/db-backup-cronjob.yaml
  - monitoring/prometheus-grafana.yaml
  - monitoring/loki-stack.yaml
  - monitoring/fluent-bit.yaml
  - monitoring/otel-collector.yaml
  - monitoring/otel-collector-monitor.yaml
  - monitoring/tempo.yaml
  - multi-region/external-dns.yaml
