apiVersion: v2
name: stateful-services
description: A Helm chart for deploying conditional stateful databases (Postgres, Redis, RabbitMQ, MongoDB) across multiple regions.
type: application
version: 0.1.1
appVersion: "1.0"
