# Default values for stateful-services.

global:
  multiRegion:
    enabled: false
  primaryRegion: "us-east"
  secondaryRegion: "eu-west"
  currentRegion: "us-east"

postgres:
  useCloudProvider: true

mongodb:
  useCloudProvider: true

redis:
  useCloudProvider: false
  storageClassName: do-block-storage
  resources:
    requests:
      cpu: "1"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

rabbitmq:
  useCloudProvider: true
