# Default values for stateful-services.

global:
  multiRegion:
    enabled: false
  primaryRegion: "us-east"
  secondaryRegion: "eu-west"
  currentRegion: "us-east"

postgres:
  useCloudProvider: true

mongodb:
  useCloudProvider: true

redis:
  useCloudProvider: false

rabbitmq:
  useCloudProvider: true
