apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chess-infra
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: https://github.com/bhatvinay7/chess-k8s.git
    targetRevision: HEAD
    path: infra
=======
    repoURL: https://github.com/your-org/chess.git
    targetRevision: HEAD
    path: k8s/infra
>>>>>>> dce2e99 (Add argocd)
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
