apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chess-apps
  namespace: argocd
<<<<<<< HEAD
  annotations:
    argocd.argoproj.io/sync-wave: "2"
=======
>>>>>>> dce2e99 (Add argocd)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
<<<<<<< HEAD
    repoURL: https://github.com/bhatvinay75/chess-k8s.git
    targetRevision: HEAD
    path: apps
=======
    repoURL: https://github.com/your-org/chess.git
    targetRevision: HEAD
    path: k8s/apps
>>>>>>> dce2e99 (Add argocd)
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: chess-secrets
      jsonPointers:
        - /data
        - /stringData
<<<<<<< HEAD
    - group: ""
      kind: Secret
      name: frontend-secrets
      jsonPointers:
        - /data
        - /stringData
    - group: ""
      kind: Secret
      name: backend-secrets
      jsonPointers:
        - /data
        - /stringData
=======
>>>>>>> dce2e99 (Add argocd)
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
