apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
type: Opaque
stringData:
  admin.password: "$2b$12$KYDlZqsolXiEYr.0lSk9XeWaQqIR28yKlyDg51o8hm0Hio0OGAgnG"
  admin.passwordMtime: "2024-01-01T00:00:00Z"
