apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stateful-services
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            deploy-stateful-services: "true"
  template:
    metadata:
      name: '{{name}}-stateful'
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: default
      source:
        repoURL: 'https://github.com/bhatvinay7/bookit-k8s.git'
        targetRevision: deployment1
        path: charts/stateful-services
        helm:
          releaseName: stateful-services
          valueFiles:
            - 'values-{{metadata.labels.environment}}.yaml'
          values: |
            postgres:
              useCloudProvider: true
            mongodb:
              useCloudProvider: true
            redis:
              useCloudProvider: false
            rabbitmq:
              useCloudProvider: false
      destination:
        server: '{{server}}'
        namespace: bookit
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
