apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: stateful-services
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            deploy-stateful-services: "true"
  template:
    metadata:
      name: '{{name}}-stateful'
    spec:
      project: default
      source:
        repoURL: 'https://github.com/bhatvinay7/bookit-k8s.git'
        targetRevision: HEAD
        path: charts/stateful-services
        helm:
          releaseName: stateful-services
          values: |
            global:
              multiRegion:
                enabled: '{{metadata.labels.multi_region_enabled}}'
              primaryRegion: '{{metadata.labels.primary_region}}'
              secondaryRegion: '{{metadata.labels.secondary_region}}'
              currentRegion: '{{metadata.labels.region}}'
            postgres:
              useCloudProvider: true
            mongodb:
              useCloudProvider: true
            redis:
              useCloudProvider: false
            rabbitmq:
              useCloudProvider: false
      destination:
        server: '{{server}}'
        namespace: bookit
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
