apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../overlays/prod
- secrets

configMapGenerator:
- name: bookit-config
  behavior: merge
  literals:
  - BOOKIT_REGION=eu-west

labels:
- pairs:
    bookit.io/region: eu-west
  includeSelectors: false
