# apiVersion: apps/v1
# kind: StatefulSet
# metadata:
#   name: mongodb-ha
#   namespace: bookit
# spec:
#   serviceName: "mongodb-ha-headless"
#   replicas: 3
#   selector:
#     matchLabels:
#       app: mongodb-ha
#   template:
#     metadata:
#       labels:
#         app: mongodb-ha
#     spec:
#       containers:
#         - name: mongodb
#           image: bitnami/mongodb:6.0
#           env:
#             - name: MONGODB_REPLICA_SET_MODE
#               value: "primary"
#             - name: MONGODB_REPLICA_SET_NAME
#               value: "rs0"
#             - name: MONGODB_ROOT_PASSWORD
#               value: "rootpassword"
#             - name: MONGODB_REPLICA_SET_KEY
#               value: "replicasetkey123"
#             - name: MONGODB_ADVERTISED_HOSTNAME
#               valueFrom:
#                 fieldRef:
#                   fieldPath: metadata.name
#           ports:
#             - containerPort: 27017
#           volumeMounts:
#             - name: data
#               mountPath: /bitnami/mongodb
#         # Metrics Exporter
#         - name: metrics
#           image: percona/mongodb_exporter:2.37
#           env:
#             - name: MONGODB_URI
#               value: "mongodb://root:rootpassword@127.0.0.1:27017/admin"
#           ports:
#             - containerPort: 9216
#               name: metrics
#   volumeClaimTemplates:
#     - metadata:
#         name: data
#       spec:
#         accessModes: [ "ReadWriteOnce" ]
#         resources:
#           requests:
#             storage: 10Gi
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb-ha-headless
#   namespace: bookit
# spec:
#   ports:
#     - port: 27017
#       name: mongodb
#   clusterIP: None
#   selector:
#     app: mongodb-ha
# ---
# # Standard Service for clients to connect (Clients must specify replicaSet=rs0 in connection string)
# apiVersion: v1
# kind: Service
# metadata:
#   name: mongodb-proxy
#   namespace: bookit
# spec:
#   ports:
#     - port: 27017
#       targetPort: 27017
#   selector:
#     app: mongodb-ha
