apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- cert-manager-issuer.yaml
- rabbitmq-client-keystore-password.yaml
- configmap.yaml
- http-server.yaml
- ws-server.yaml
- gateway-keeper.yaml
- lock-server.yaml
- notification-worker.yaml
- payment-processor.yaml
- search-server.yaml
- web.yaml
- ingress.yaml
- grpc-ingress.yaml

patches:
- target:
    kind: Deployment
    name: (gateway-keeper|http-server|lock-server|notification-worker|payment-processor)
  patch: |-
    - op: add
      path: /spec/template/spec/volumes
      value:
      - name: rabbitmq-client-pem
        secret:
          secretName: rabbitmq-client-tls
      - name: rabbitmq-server-ca
        secret:
          secretName: rabbitmq-server-tls
          items:
          - key: ca.crt
            path: ca.crt
    - op: add
      path: /spec/template/spec/containers/0/volumeMounts
      value:
      - name: rabbitmq-client-pem
        mountPath: /rabbitmq-pem
        readOnly: true
      - name: rabbitmq-server-ca
        mountPath: /rabbitmq-ca
        readOnly: true
- target:
    kind: Deployment
    name: (http-server|notification-worker|payment-processor)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
      - name: RABBITMQ_URL
        value: amqps://rabbitmq.bookit.svc.cluster.local:5671/%2f?auth_mechanism=external
      - name: RABBITMQ_TLS_CA_PATH
        value: /rabbitmq-ca/ca.crt
      - name: RABBITMQ_TLS_IDENTITY_PATH
        value: /rabbitmq-pem/keystore.p12
      - name: RABBITMQ_TLS_IDENTITY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rabbitmq-client-keystore-password
            key: password
- target:
    kind: Deployment
    name: (gateway-keeper|lock-server)
  patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: RABBITMQ_URL
        value: amqps://rabbitmq.bookit.svc.cluster.local:5671/%2f?auth_mechanism=external
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: RABBITMQ_TLS_CA_PATH
        value: /rabbitmq-ca/ca.crt
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: RABBITMQ_TLS_IDENTITY_PATH
        value: /rabbitmq-pem/keystore.p12
    - op: add
      path: /spec/template/spec/containers/0/env/-
      value:
        name: RABBITMQ_TLS_IDENTITY_PASSWORD
        valueFrom:
          secretKeyRef:
            name: rabbitmq-client-keystore-password
            key: password
