apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- cert-manager-issuer.yaml
- configmap.yaml
- http-server.yaml
- ws-server.yaml
- gateway-keeper.yaml
- lock-server.yaml
- notification-worker.yaml
- payment-processor.yaml
- search-server.yaml
- web.yaml
- ingress.yaml
- grpc-ingress.yaml

# CI/CD (GitHub Actions) updates newTag to the latest build commit SHA
images:
- name: bookit-gateway-keeper
  newName: ghcr.io/bhatvinay7/bookit-gateway-keeper
  newTag: commit-d6533e8
- name: bookit-lock-server
  newName: ghcr.io/bhatvinay7/bookit-lock-server
  newTag: commit-d6533e8
- name: bookit-http-server
  newName: ghcr.io/bhatvinay7/bookit-http-server
  newTag: commit-d6533e8
- name: bookit-notification-worker
  newName: ghcr.io/bhatvinay7/bookit-notification-worker
  newTag: commit-d6533e8
- name: bookit-payment-processor
  newName: ghcr.io/bhatvinay7/bookit-payment-processor
  newTag: commit-d6533e8
- name: bookit-search-server
  newName: ghcr.io/bhatvinay7/bookit-search-server
  newTag: commit-d6533e8
- name: bookit-web
  newName: ghcr.io/bhatvinay7/bookit-web
  newTag: commit-661b76d
- name: bookit-ws-server
  newName: ghcr.io/bhatvinay7/bookit-ws-server
  newTag: commit-d6533e8
