apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- cert-manager-issuer.yaml
- configmap.yaml
- http-server.yaml
- ws-server.yaml
- gateway-keeper.yaml
- lock-server.yaml
- notification-worker.yaml
- payment-processor.yaml
- search-server.yaml
- web.yaml
- ingress.yaml
- grpc-ingress.yaml

