apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lock-server
  name: lock-server
  namespace: bookit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lock-server
  template:
    metadata:
      labels:
        app: lock-server
    spec:
      containers:
      - env:
        - name: LOCK_WORKER_CONCURRENCY
          value: '10'
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: bookit-config
        image: bookit-lock-server:latest
        imagePullPolicy: Always
        name: lock-server
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      imagePullSecrets:
      - name: ghcr-secret
