apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: lock-server
  name: lock-server
  namespace: bookit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lock-server
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: '80'
        prometheus.io/scrape: 'true'
      labels:
        app: lock-server
    spec:
      containers:
      - env:
        - name: LOCK_WORKER_CONCURRENCY
          value: '10'
        envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: bookit-config
        image: ghcr.io/bhatvinay7/bookit-lock-server:latest
        imagePullPolicy: Always
        name: lock-server
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: lock-server-hpa
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: lock-server
