apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-worker
  name: notification-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: backend-secrets
        - secretRef:
            name: bookit-secrets
        - configMapRef:
            name: bookit-config
        env:
        # Use port 587 (STARTTLS) for Gmail SMTP as requested.
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_HOST
          value: "smtp.gmail.com"
        image: bookit-notification-worker:latest
        name: notification-worker
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
      imagePullSecrets:
      - name: ghcr-secret
      serviceAccountName: bookit-app
