apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: payment-processor
  name: payment-processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-processor
  template:
    metadata:
      labels:
        app: payment-processor
    spec:
      containers:
        - envFrom:
            - secretRef:
                name: backend-secrets
            - configMapRef:
                name: bookit-config
          env:
            - name: OTEL_SERVICE_NAME
              value: bookit-payment-processor
            - name: K8S_NAMESPACE
              valueFrom: { fieldRef: { fieldPath: metadata.namespace } }
            - name: POD_NAME
              valueFrom: { fieldRef: { fieldPath: metadata.name } }
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: k8s.namespace.name=$(K8S_NAMESPACE),k8s.pod.name=$(POD_NAME)
          image: bookit-payment-processor:latest
          name: payment-processor
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi
      imagePullSecrets:
        - name: ghcr-secret
      serviceAccountName: bookit-app
