apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: search-server
  name: search-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: search-server
  template:
    metadata:
      labels:
        app: search-server
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: backend-secrets
        - configMapRef:
            name: bookit-config
        image: ghcr.io/bhatvinay7/bookit-search-server:latest
        name: search-server
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      imagePullSecrets:
      - name: ghcr-secret
      serviceAccountName: bookit-app
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: search-server-hpa
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 75
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: search-server
