apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookit-apps-monitor
  namespace: bookit
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    release: prometheus
spec:
  selector:
    matchExpressions:
      - key: app
        operator: Exists
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
      - bookit
