apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    release: prometheus
  name: bookit-apps-monitor
  namespace: bookit
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - bookit
  selector:
    matchExpressions:
    - key: app
      operator: Exists
