apiVersion: v1
kind: ConfigMap
metadata:
  name: bookit-config
  labels:
    app: chess
data:
  # App configs
  HTTP_PORT: "3002"
  WS_PORT: "8080"
  GRPC_PORT: "50051"
  METRICS_PORT: "9100"
  LOG_LEVEL: "info"
  NODE_ENV: "production"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring.svc.cluster.local:4317"
