apiVersion: v1
kind: Service
metadata:
  name: game-server-headless
  labels:
    app: game-server
spec:
  clusterIP: None
  ports:
    - port: 50051
      targetPort: 50051
      name: grpc
  selector:
    app: game-server
