apiVersion: v1
kind: Secret
metadata:
  name: ghcr-secret
  labels:
    app: chess
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "ghcr.io": {
          "username": "bhatvinay7",
          "password": "${{ secrets.GITOPS_TOKEN }}",
          "email": "bhatvinay75@gmail.com",
          "auth": "${{ secrets.GITOPS_TOKEN }}"
        }
      }
    }
