apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chess-ingress
  labels:
    app: chess
  annotations:
<<<<<<< HEAD
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
=======
    kubernetes.io/ingress.class: "nginx"
>>>>>>> dce2e99 (Add argocd)
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/websocket-services: "ws-server"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
<<<<<<< HEAD
  ingressClassName: nginx
  tls:
    - hosts:
        - api.chesscounty.life
        - ws.chesscounty.life
        - web.chesscounty.life
        - chesscounty.life
      secretName: chesscounty-life-tls
  rules:
    - host: api.chesscounty.life
      http:
        paths:
          - path: /
=======
  rules:
    - host: chess.example.com
      http:
        paths:
          - path: /api
>>>>>>> dce2e99 (Add argocd)
            pathType: Prefix
            backend:
              service:
                name: http-server
                port:
                  number: 3002
<<<<<<< HEAD
    - host: ws.chesscounty.life
      http:
        paths:
          - path: /
=======
          - path: /ws
>>>>>>> dce2e99 (Add argocd)
            pathType: Prefix
            backend:
              service:
                name: ws-server
                port:
                  number: 8080
<<<<<<< HEAD
    - host: web.chesscounty.life
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
    - host: chesscounty.life
      http:
        paths:
=======
>>>>>>> dce2e99 (Add argocd)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 3000
