apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  labels:
    app: notification-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
<<<<<<< HEAD
      serviceAccountName: chess-app
=======
>>>>>>> dce2e99 (Add argocd)
      containers:
        - name: notification-worker
          image: chess-notification-worker:latest
          envFrom:
            - secretRef:
<<<<<<< HEAD
                name: backend-secrets
=======
                name: chess-secrets
>>>>>>> dce2e99 (Add argocd)
            - configMapRef:
                name: chess-config
          ports:
            - containerPort: 9104
              name: metrics
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
