apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-worker
  labels:
    app: notification-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-worker
  template:
    metadata:
      labels:
        app: notification-worker
    spec:
      serviceAccountName: chess-app
      containers:
        - name: notification-worker
          image: chess-notification-worker:latest
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          envFrom:
            - secretRef:
                name: backend-secrets
            - configMapRef:
                name: chess-config
          ports:
            - containerPort: 9104
              name: metrics
