apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-server
  labels:
    app: ws-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ws-server
  template:
    metadata:
      labels:
        app: ws-server
    spec:
<<<<<<< HEAD
      serviceAccountName: chess-app
=======
>>>>>>> dce2e99 (Add argocd)
      containers:
        - name: ws-server
          image: chess-ws-server:latest
          envFrom:
            - secretRef:
<<<<<<< HEAD
                name: backend-secrets
=======
                name: chess-secrets
>>>>>>> dce2e99 (Add argocd)
            - configMapRef:
                name: chess-config
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 150m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: ws-server
  labels:
    app: ws-server
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: ws-server
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ws-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ws-server
  minReplicas: 1
  maxReplicas: 1
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
